final int SCREEN_X = 885;
final int SCREEN_Y = 900;
int NO_OF_BULLETS = 1;
final int NO_OF_ALIENS = 10;
int NO_OF_ALIEN_ROWS = 1;
final int MAX_ROWS = 9;
int bulletSpeed;
int piercingBullets;
int aliensKilled;
boolean reset = false;
boolean gameStart = false;
final int MAX_LIVES = 3;
int playerLives = 3;
final int OFFSCREEN = -100;
int hitFrameCounter = 0;
